### ISSUE TITLE
Create build script to allow static compilation

### ISSUE THREAD

**Issue by paradigm** [gcmurphy/rust-capabilities#2]
I'd like to statically link libcap into my project.  I have compiled a libcap against musl, but I am unable to direct cargo to use this with the rust-capabilities crate as-is due to the [hardcoded `#[link(name="cap")]`](https://github.com/gcmurphy/rust-capabilities/blob/ae0995581fa4a03d66c0fb228c017d88c374795f/src/lib.rs#L27).  After asking in #cargo, it seems the preferred solution going forward is to have crates like rust-capabilities create a build script which reads environment variables to determine both whether to link dynamically or statically as well as where to find the library to link against.  [rust-openssl's build script is a good example of this](https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/build.rs) - note the `OPENSSL_LIB_DIR` and `OPENSSL_STATIC`.  Presumably we'd want something like a `CAPABILITIES_LIB_DIR` and `CAPABILITIES_STATIC`.  Given that it can continue to operate as it currently does if the environment variables are absent, I do not believe this would be a breaking change.

**Comment by gcmurphy** [comment]
Hmm ok. Would something like this work for you? 

```rust
// build.rs
use std::env;

fn main() {

    let rustc_link_lib = match env::var("LIBCAP_LIB_NAME") {
        Ok(name) => name, // or your custom library name
        Err(_) => String::from("cap"),
    };

    let rustc_link_type = match env::var("LIBCAP_LIB_TYPE") {
        Ok(mode) => mode, // static, dylib, framework
        Err(_) => String::from("dylib"),
    };

    println!("cargo:rustc-link-lib={}={}",
             rustc_link_type,
             rustc_link_lib);

    match env::var("LIBCAP_LIB_PATH") {
        Ok(rustc_link_search) => println!("cargo:rustc-link-search=native={}", rustc_link_search),
        Err(_) => {} // use LD_LIBRARY_PATH
    };
}
```

I *think* you should be able to link statically via: 

`$ LIBCAP_LIB_TYPE=static LIBCAP_LIB_PATH=/path/to/static/libdir cargo build`

**Comment by paradigm** [comment]
Perfect, thanks!
