### ISSUE TITLE
from_current_proc and friends should return Result

### ISSUE THREAD

**Issue by mlafeldt** [gcmurphy/rust-capabilities#4]
Hey,

Thanks for this great lib!

One thing I found weird when integrating it in our codebase is that [from_current_proc][1] and other functions return an `Option` when the result should really be, well, a `Result` -- to indicate success or failure.

[1]: https://github.com/gcmurphy/rust-capabilities/blob/d0a7d57f3b07a7b1be3d40c09eefba9fd603e6e3/src/lib.rs#L506-L512

According to https://linux.die.net/man/3/cap_get_proc, `cap_get_proc` returns NULL to indicate a failure. In that case, `from_current_proc` should return an error instead of `None`. As a user of this lib, I don't really know what `None` is supposed to mean here (I ended up converting it to an error).

**Comment by gcmurphy** [comment]
I agree. @mlafeldt does https://github.com/gcmurphy/rust-capabilities/pull/5 look more reasonable?

**Comment by mlafeldt** [comment]
That looks really good! Thank you.

**Comment by gcmurphy** [comment]
Published a new crate with this fix in it. Closing. https://crates.io/crates/capabilities
